# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbc9abe07439e5da771a6a0de04762efb1509350bf3b5c6bd3125a98f417faa276494ff4f6e44684700d1344cefaa17205c8e31dff8f5c64e067b333f52e0c56

test:
  secret_key_base: 5376c225ad8cf613318bbe0a6c55136597bd7b00057384ba9d0ba54da8064985273054c2918cc5a2ca61d0e793587c2e665026c052b7d55057b8d424b5f35402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
